# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: marcela
    # (this is just an example, not intended to be a production configuration)
    ports: 
      - "3306:3306"
